### ISSUE TITLE
hackage

### ISSUE THREAD

**Issue by tonyday567** [ku-fpg/javascript-bridge#1]
Hi,

Any chance this library could go on hackage? It's a nice library, I use it to good effect and it fills a niche I can't find elsewhere.

**Comment by andygill** [comment]
Tony,

Glad you like the package. I plan to push this to hackage before the semester starts (within a month or so). Will this work? I've got a number of planned tools that will depend on it.

Andy

**Comment by tonyday567** [comment]
Works well for me, thanks.  Look forward to seeing the resultant toolset.

**Comment by andygill** [comment]
Pushed to hackage.
